### ISSUE TITLE
Display logic not working on ItemEditForm

### ISSUE THREAD

**Issue by ss-koshala** [unclecheese/silverstripe-display-logic#118] opened 2020-08-20 08:44 UTC
display logic not working on ItemEditForm.
 ` "silverstripe/recipe-plugin": `"^1.2",`
 ` "silverstripe/recipe-cms": "4.6.0@stable",`

**Comment by michalkleiner** [comment] 2023-02-15 03:08
Duplicate of #105

**Closed by michalkleiner** 2023-02-15 03:08 UTC
